### ISSUE TITLE
supertab and neosnippet have conflict

### ISSUE THREAD

**Issue by tcstory** [Shougo/neosnippet.vim#227]
sorry，my english is poor
supertab and neosnippet are both the newset version, I installed them by using vundle yesterday，the version of vim is version 7.4.52 ,and it also support Scripting language（e.g. perl  or lua).But when i set up supertab and neosnippet simultaneously,the supertab is working,but neosnippet is not,i can't use <c-k> to expand a snippet,but when i disable supertab,the neosnippet is working properly................so , i think there is a conflict between the two plugins........
Is there any way to solve this problem?

**Comment by chrisduerr** [comment]
@Shougo I know this has been closed for a long time but I feel like I'm running into this exact issue. I am using deoplete and for making it autocomplete using <TAB> I installed SuperTab. Now the issue is that because SuperTab is installed I cannot expand snippets using <TAB> anymore.

Is it impossible to have tab autocompletion for both deoplete and neosnippet? I'd like to be able to go through the recommendations hitting tab and then just start writing after the correct one got selected.

**Comment by wsdjeg** [comment]
I use tab for deoplete completion and neosnippet expand at same time. may be you can have a look at my Dotfiles repo.

**Comment by chrisduerr** [comment]
@wsdjeg thanks that helped me a lot! I think I can get it to work using a custom Tab function even tho I have problems with <Plug>(neosnippet_expand) but I'm sure I'll figure that out.

So I guess yeah SuperTab doesn't work but there are alternative ways to do this.

**Comment by wsdjeg** [comment]
Yeah I do no use supertab.
